services:
  calc:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: calc
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: calc-api
    restart: unless-stopped
